export const actionTypes = {
    FAILURE: 'FAILURE',
    LOAD_NEWS: 'LOAD_NEWS',
    LOAD_NEWS_SUCCESS: 'LOAD_NEWS_SUCCESS',
    ADD_CURRENT_CATEGORY: 'ADD_CURRENT_CATEGORY',
    ADD_NEW_CATEGORY: 'ADD_NEW_CATEGORY',
    LOAD_CATEGORIES: 'LOAD_CATEGORIES',
    ADD_CATEGORY_IN_LIST: 'ADD_CATEGORY_IN_LIST',
    CHANGE_LOADING_STATE: 'CHANGE_LOADING_STATE',
};
